### ISSUE TITLE
population: invalid choice: 'F3' 

### ISSUE THREAD

**Issue by mictadlo** [freemao/schnablelab#3]
Hi,
We have one population consisted of 192 F3 lines resulting from a cross between two plant genomes.

```
python -m schnablelab.imputation.GC qc_sd gc-missing.map gc-sdtest.map --population F3
GC.py: error: option --population: invalid choice: 'F3' (choose from 'RIL', 'F2', 'BCFn')
```

Should I use `--population F2` despite I have F3?

Thank you in advance,

Michal

**Comment by freemao** [comment]
Hi Michal,

F3 is RIL3 so just set the population type to RIL

Best
Chenyong

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
