### ISSUE TITLE
Genotype corrector: TypeError: apply() got an unexpected keyword argument 'raw'

### ISSUE THREAD

**Issue by ramesh8v** [freemao/schnablelab#4]
Hello,

**My Python version:** Python 3.6.6 :: Anaconda, Inc.
**Pandas version:** '0.22.0'
**Numpy version:** '1.14.0'

**When I executed this command:**  python -m schnablelab.imputation.GC correct config.txt raw_output_50.map --debug

**I ended up getting this error:** 
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ramesh8v/genotype_corrector/schnablelab/imputation/GC.py", line 921, in <module>
    main()
  File "/home/ramesh8v/genotype_corrector/schnablelab/imputation/GC.py", line 918, in main
    p.dispatch(globals())
  File "/home/ramesh8v/genotype_corrector/schnablelab/apps/base.py", line 84, in dispatch
    globals[action](sys.argv[2:])
  File "/home/ramesh8v/genotype_corrector/schnablelab/imputation/GC.py", line 315, in correct
    correct_obj = CorrectOO(cargs, seq_no_idx_num)
  File "/home/ramesh8v/genotype_corrector/schnablelab/imputation/GC.py", line 219, in __init__
    self.rolling_geno = self.seq_num_no1.rolling(self.cargs.win_size, center=True).apply(get_mid_geno, raw=True, args=(self.cargs,))
TypeError: apply() got an unexpected keyword argument 'raw'

Thanks, 
Ramesh

**Comment by freemao** [comment]
Hi Ramesh, 
Can you try to run the below command under the `schnablelab/imputation/tests` directory:
`python -m schnablelab.imputation.GC correct config.txt RIL_Medicago.map`
If it can be run without any error, which means your input map file has some problems. If it returns the same error, which means the conda running environment has some issues.

**Comment by ramesh8v** [comment]
Hi Freemao,

It's returning the same error even when I run inside the tests directory.

**Comment by freemao** [comment]
Okay. Then I will prepare an installation file including all the packages with version info for you to set up the conda environment later today.


On Nov 21, 2019, at 12:46 PM, Ramesh Krishnan Ramasamy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Freemao,

It's returning the same error even when I run inside the tests directory.

**Comment by ramesh8v** [comment]
Excellent! thanks

**Comment by freemao** [comment]
I just uploaded a file named 'spec_file.csv' including all dependent libraries to the schnablelab repository. You can set up the running env using the below commands
``` 
conda create --name my_env --file spec_file.csv
conda activate my_env
python -m schnablelab ...
```
Let me know if this works for you. Remember to try different the sliding window sizes.

**Comment by ramesh8v** [comment]
Hi Freemao,
Thanks. Your spec file doesn't mention any package and their version, or am I missing something? or can I just install the most recent version of numpy, Pandas, Scipy ..... ?

**Comment by freemao** [comment]
Ohh, sorry. That's not the file I was going to upload. I will fixe it

**Comment by ramesh8v** [comment]
No problem, I installed the most recent of all required packages. It seems working!! I'll update you here

**Comment by freemao** [comment]
I have uploaded the right one I am using

**Comment by ramesh8v** [comment]
Thanks! My installation is working without any error. I installed the most recent versions using conda and pip install.
